//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace praktikfall.WebServiceUpg1Reference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://brokerapplication.org/", ConfigurationName="WebServiceUpg1Reference.WebServiceUpg1Soap")]
    public interface WebServiceUpg1Soap {
        
        // CODEGEN: Generating message contract since element name filepath from namespace http://brokerapplication.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://brokerapplication.org/GetFileContent", ReplyAction="*")]
        praktikfall.WebServiceUpg1Reference.GetFileContentResponse GetFileContent(praktikfall.WebServiceUpg1Reference.GetFileContentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://brokerapplication.org/GetFileContent", ReplyAction="*")]
        System.Threading.Tasks.Task<praktikfall.WebServiceUpg1Reference.GetFileContentResponse> GetFileContentAsync(praktikfall.WebServiceUpg1Reference.GetFileContentRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFileContentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFileContent", Namespace="http://brokerapplication.org/", Order=0)]
        public praktikfall.WebServiceUpg1Reference.GetFileContentRequestBody Body;
        
        public GetFileContentRequest() {
        }
        
        public GetFileContentRequest(praktikfall.WebServiceUpg1Reference.GetFileContentRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://brokerapplication.org/")]
    public partial class GetFileContentRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string filepath;
        
        public GetFileContentRequestBody() {
        }
        
        public GetFileContentRequestBody(string filepath) {
            this.filepath = filepath;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFileContentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFileContentResponse", Namespace="http://brokerapplication.org/", Order=0)]
        public praktikfall.WebServiceUpg1Reference.GetFileContentResponseBody Body;
        
        public GetFileContentResponse() {
        }
        
        public GetFileContentResponse(praktikfall.WebServiceUpg1Reference.GetFileContentResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://brokerapplication.org/")]
    public partial class GetFileContentResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetFileContentResult;
        
        public GetFileContentResponseBody() {
        }
        
        public GetFileContentResponseBody(string GetFileContentResult) {
            this.GetFileContentResult = GetFileContentResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceUpg1SoapChannel : praktikfall.WebServiceUpg1Reference.WebServiceUpg1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceUpg1SoapClient : System.ServiceModel.ClientBase<praktikfall.WebServiceUpg1Reference.WebServiceUpg1Soap>, praktikfall.WebServiceUpg1Reference.WebServiceUpg1Soap {
        
        public WebServiceUpg1SoapClient() {
        }
        
        public WebServiceUpg1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceUpg1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceUpg1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceUpg1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        praktikfall.WebServiceUpg1Reference.GetFileContentResponse praktikfall.WebServiceUpg1Reference.WebServiceUpg1Soap.GetFileContent(praktikfall.WebServiceUpg1Reference.GetFileContentRequest request) {
            return base.Channel.GetFileContent(request);
        }
        
        public string GetFileContent(string filepath) {
            praktikfall.WebServiceUpg1Reference.GetFileContentRequest inValue = new praktikfall.WebServiceUpg1Reference.GetFileContentRequest();
            inValue.Body = new praktikfall.WebServiceUpg1Reference.GetFileContentRequestBody();
            inValue.Body.filepath = filepath;
            praktikfall.WebServiceUpg1Reference.GetFileContentResponse retVal = ((praktikfall.WebServiceUpg1Reference.WebServiceUpg1Soap)(this)).GetFileContent(inValue);
            return retVal.Body.GetFileContentResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<praktikfall.WebServiceUpg1Reference.GetFileContentResponse> praktikfall.WebServiceUpg1Reference.WebServiceUpg1Soap.GetFileContentAsync(praktikfall.WebServiceUpg1Reference.GetFileContentRequest request) {
            return base.Channel.GetFileContentAsync(request);
        }
        
        public System.Threading.Tasks.Task<praktikfall.WebServiceUpg1Reference.GetFileContentResponse> GetFileContentAsync(string filepath) {
            praktikfall.WebServiceUpg1Reference.GetFileContentRequest inValue = new praktikfall.WebServiceUpg1Reference.GetFileContentRequest();
            inValue.Body = new praktikfall.WebServiceUpg1Reference.GetFileContentRequestBody();
            inValue.Body.filepath = filepath;
            return ((praktikfall.WebServiceUpg1Reference.WebServiceUpg1Soap)(this)).GetFileContentAsync(inValue);
        }
    }
}
