//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace praktikfall.WebServiceUpg2Reference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ObjectOwner", Namespace="http://brokerapplication.org/")]
    [System.SerializableAttribute()]
    public partial class ObjectOwner : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OwnerSsnrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string OwnerSsnr {
            get {
                return this.OwnerSsnrField;
            }
            set {
                if ((object.ReferenceEquals(this.OwnerSsnrField, value) != true)) {
                    this.OwnerSsnrField = value;
                    this.RaisePropertyChanged("OwnerSsnr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string PhoneNr {
            get {
                return this.PhoneNrField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNrField, value) != true)) {
                    this.PhoneNrField = value;
                    this.RaisePropertyChanged("PhoneNr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RealEstateBroker", Namespace="http://brokerapplication.org/")]
    [System.SerializableAttribute()]
    public partial class RealEstateBroker : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BrokerSsnrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BrokerAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string BrokerSsnr {
            get {
                return this.BrokerSsnrField;
            }
            set {
                if ((object.ReferenceEquals(this.BrokerSsnrField, value) != true)) {
                    this.BrokerSsnrField = value;
                    this.RaisePropertyChanged("BrokerSsnr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string BrokerAddress {
            get {
                return this.BrokerAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.BrokerAddressField, value) != true)) {
                    this.BrokerAddressField = value;
                    this.RaisePropertyChanged("BrokerAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string PhoneNr {
            get {
                return this.PhoneNrField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNrField, value) != true)) {
                    this.PhoneNrField = value;
                    this.RaisePropertyChanged("PhoneNr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Showing", Namespace="http://brokerapplication.org/")]
    [System.SerializableAttribute()]
    public partial class Showing : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int ObjNrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BuyerSsnrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShowingDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ObjNr {
            get {
                return this.ObjNrField;
            }
            set {
                if ((this.ObjNrField.Equals(value) != true)) {
                    this.ObjNrField = value;
                    this.RaisePropertyChanged("ObjNr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string BuyerSsnr {
            get {
                return this.BuyerSsnrField;
            }
            set {
                if ((object.ReferenceEquals(this.BuyerSsnrField, value) != true)) {
                    this.BuyerSsnrField = value;
                    this.RaisePropertyChanged("BuyerSsnr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ShowingDate {
            get {
                return this.ShowingDateField;
            }
            set {
                if ((object.ReferenceEquals(this.ShowingDateField, value) != true)) {
                    this.ShowingDateField = value;
                    this.RaisePropertyChanged("ShowingDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProspectiveBuyer", Namespace="http://brokerapplication.org/")]
    [System.SerializableAttribute()]
    public partial class ProspectiveBuyer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BuyerSsnrField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string PhoneNr {
            get {
                return this.PhoneNrField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNrField, value) != true)) {
                    this.PhoneNrField = value;
                    this.RaisePropertyChanged("PhoneNr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string BuyerSsnr {
            get {
                return this.BuyerSsnrField;
            }
            set {
                if ((object.ReferenceEquals(this.BuyerSsnrField, value) != true)) {
                    this.BuyerSsnrField = value;
                    this.RaisePropertyChanged("BuyerSsnr");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RealEstateObject", Namespace="http://brokerapplication.org/")]
    [System.SerializableAttribute()]
    public partial class RealEstateObject : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageField;
        
        private int ObjnrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ObjAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ObjCityField;
        
        private int ObjPriceField;
        
        private int ObjAreaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ObjRoomsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UnitTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ObjInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BrokerSsnrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OwnerSsnrField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Image {
            get {
                return this.ImageField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageField, value) != true)) {
                    this.ImageField = value;
                    this.RaisePropertyChanged("Image");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Objnr {
            get {
                return this.ObjnrField;
            }
            set {
                if ((this.ObjnrField.Equals(value) != true)) {
                    this.ObjnrField = value;
                    this.RaisePropertyChanged("Objnr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ObjAddress {
            get {
                return this.ObjAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.ObjAddressField, value) != true)) {
                    this.ObjAddressField = value;
                    this.RaisePropertyChanged("ObjAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ObjCity {
            get {
                return this.ObjCityField;
            }
            set {
                if ((object.ReferenceEquals(this.ObjCityField, value) != true)) {
                    this.ObjCityField = value;
                    this.RaisePropertyChanged("ObjCity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int ObjPrice {
            get {
                return this.ObjPriceField;
            }
            set {
                if ((this.ObjPriceField.Equals(value) != true)) {
                    this.ObjPriceField = value;
                    this.RaisePropertyChanged("ObjPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int ObjArea {
            get {
                return this.ObjAreaField;
            }
            set {
                if ((this.ObjAreaField.Equals(value) != true)) {
                    this.ObjAreaField = value;
                    this.RaisePropertyChanged("ObjArea");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string ObjRooms {
            get {
                return this.ObjRoomsField;
            }
            set {
                if ((object.ReferenceEquals(this.ObjRoomsField, value) != true)) {
                    this.ObjRoomsField = value;
                    this.RaisePropertyChanged("ObjRooms");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string UnitType {
            get {
                return this.UnitTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.UnitTypeField, value) != true)) {
                    this.UnitTypeField = value;
                    this.RaisePropertyChanged("UnitType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string ObjInfo {
            get {
                return this.ObjInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.ObjInfoField, value) != true)) {
                    this.ObjInfoField = value;
                    this.RaisePropertyChanged("ObjInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string BrokerSsnr {
            get {
                return this.BrokerSsnrField;
            }
            set {
                if ((object.ReferenceEquals(this.BrokerSsnrField, value) != true)) {
                    this.BrokerSsnrField = value;
                    this.RaisePropertyChanged("BrokerSsnr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string OwnerSsnr {
            get {
                return this.OwnerSsnrField;
            }
            set {
                if ((object.ReferenceEquals(this.OwnerSsnrField, value) != true)) {
                    this.OwnerSsnrField = value;
                    this.RaisePropertyChanged("OwnerSsnr");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://brokerapplication.org/", ConfigurationName="WebServiceUpg2Reference.WebServiceUpg2Soap")]
    public interface WebServiceUpg2Soap {
        
        // CODEGEN: Generating message contract since element name GetObjectOwnerResult from namespace http://brokerapplication.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://brokerapplication.org/GetObjectOwner", ReplyAction="*")]
        praktikfall.WebServiceUpg2Reference.GetObjectOwnerResponse GetObjectOwner(praktikfall.WebServiceUpg2Reference.GetObjectOwnerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://brokerapplication.org/GetObjectOwner", ReplyAction="*")]
        System.Threading.Tasks.Task<praktikfall.WebServiceUpg2Reference.GetObjectOwnerResponse> GetObjectOwnerAsync(praktikfall.WebServiceUpg2Reference.GetObjectOwnerRequest request);
        
        // CODEGEN: Generating message contract since element name GetRealEstateBrokerResult from namespace http://brokerapplication.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://brokerapplication.org/GetRealEstateBroker", ReplyAction="*")]
        praktikfall.WebServiceUpg2Reference.GetRealEstateBrokerResponse GetRealEstateBroker(praktikfall.WebServiceUpg2Reference.GetRealEstateBrokerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://brokerapplication.org/GetRealEstateBroker", ReplyAction="*")]
        System.Threading.Tasks.Task<praktikfall.WebServiceUpg2Reference.GetRealEstateBrokerResponse> GetRealEstateBrokerAsync(praktikfall.WebServiceUpg2Reference.GetRealEstateBrokerRequest request);
        
        // CODEGEN: Generating message contract since element name GetShowingResult from namespace http://brokerapplication.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://brokerapplication.org/GetShowing", ReplyAction="*")]
        praktikfall.WebServiceUpg2Reference.GetShowingResponse GetShowing(praktikfall.WebServiceUpg2Reference.GetShowingRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://brokerapplication.org/GetShowing", ReplyAction="*")]
        System.Threading.Tasks.Task<praktikfall.WebServiceUpg2Reference.GetShowingResponse> GetShowingAsync(praktikfall.WebServiceUpg2Reference.GetShowingRequest request);
        
        // CODEGEN: Generating message contract since element name GetProspectiveBuyersResult from namespace http://brokerapplication.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://brokerapplication.org/GetProspectiveBuyers", ReplyAction="*")]
        praktikfall.WebServiceUpg2Reference.GetProspectiveBuyersResponse GetProspectiveBuyers(praktikfall.WebServiceUpg2Reference.GetProspectiveBuyersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://brokerapplication.org/GetProspectiveBuyers", ReplyAction="*")]
        System.Threading.Tasks.Task<praktikfall.WebServiceUpg2Reference.GetProspectiveBuyersResponse> GetProspectiveBuyersAsync(praktikfall.WebServiceUpg2Reference.GetProspectiveBuyersRequest request);
        
        // CODEGEN: Generating message contract since element name GetRealEstateObjectsResult from namespace http://brokerapplication.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://brokerapplication.org/GetRealEstateObjects", ReplyAction="*")]
        praktikfall.WebServiceUpg2Reference.GetRealEstateObjectsResponse GetRealEstateObjects(praktikfall.WebServiceUpg2Reference.GetRealEstateObjectsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://brokerapplication.org/GetRealEstateObjects", ReplyAction="*")]
        System.Threading.Tasks.Task<praktikfall.WebServiceUpg2Reference.GetRealEstateObjectsResponse> GetRealEstateObjectsAsync(praktikfall.WebServiceUpg2Reference.GetRealEstateObjectsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetObjectOwnerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetObjectOwner", Namespace="http://brokerapplication.org/", Order=0)]
        public praktikfall.WebServiceUpg2Reference.GetObjectOwnerRequestBody Body;
        
        public GetObjectOwnerRequest() {
        }
        
        public GetObjectOwnerRequest(praktikfall.WebServiceUpg2Reference.GetObjectOwnerRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetObjectOwnerRequestBody {
        
        public GetObjectOwnerRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetObjectOwnerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetObjectOwnerResponse", Namespace="http://brokerapplication.org/", Order=0)]
        public praktikfall.WebServiceUpg2Reference.GetObjectOwnerResponseBody Body;
        
        public GetObjectOwnerResponse() {
        }
        
        public GetObjectOwnerResponse(praktikfall.WebServiceUpg2Reference.GetObjectOwnerResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://brokerapplication.org/")]
    public partial class GetObjectOwnerResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<praktikfall.WebServiceUpg2Reference.ObjectOwner> GetObjectOwnerResult;
        
        public GetObjectOwnerResponseBody() {
        }
        
        public GetObjectOwnerResponseBody(System.Collections.Generic.List<praktikfall.WebServiceUpg2Reference.ObjectOwner> GetObjectOwnerResult) {
            this.GetObjectOwnerResult = GetObjectOwnerResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRealEstateBrokerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRealEstateBroker", Namespace="http://brokerapplication.org/", Order=0)]
        public praktikfall.WebServiceUpg2Reference.GetRealEstateBrokerRequestBody Body;
        
        public GetRealEstateBrokerRequest() {
        }
        
        public GetRealEstateBrokerRequest(praktikfall.WebServiceUpg2Reference.GetRealEstateBrokerRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetRealEstateBrokerRequestBody {
        
        public GetRealEstateBrokerRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRealEstateBrokerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRealEstateBrokerResponse", Namespace="http://brokerapplication.org/", Order=0)]
        public praktikfall.WebServiceUpg2Reference.GetRealEstateBrokerResponseBody Body;
        
        public GetRealEstateBrokerResponse() {
        }
        
        public GetRealEstateBrokerResponse(praktikfall.WebServiceUpg2Reference.GetRealEstateBrokerResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://brokerapplication.org/")]
    public partial class GetRealEstateBrokerResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<praktikfall.WebServiceUpg2Reference.RealEstateBroker> GetRealEstateBrokerResult;
        
        public GetRealEstateBrokerResponseBody() {
        }
        
        public GetRealEstateBrokerResponseBody(System.Collections.Generic.List<praktikfall.WebServiceUpg2Reference.RealEstateBroker> GetRealEstateBrokerResult) {
            this.GetRealEstateBrokerResult = GetRealEstateBrokerResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetShowingRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetShowing", Namespace="http://brokerapplication.org/", Order=0)]
        public praktikfall.WebServiceUpg2Reference.GetShowingRequestBody Body;
        
        public GetShowingRequest() {
        }
        
        public GetShowingRequest(praktikfall.WebServiceUpg2Reference.GetShowingRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetShowingRequestBody {
        
        public GetShowingRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetShowingResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetShowingResponse", Namespace="http://brokerapplication.org/", Order=0)]
        public praktikfall.WebServiceUpg2Reference.GetShowingResponseBody Body;
        
        public GetShowingResponse() {
        }
        
        public GetShowingResponse(praktikfall.WebServiceUpg2Reference.GetShowingResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://brokerapplication.org/")]
    public partial class GetShowingResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<praktikfall.WebServiceUpg2Reference.Showing> GetShowingResult;
        
        public GetShowingResponseBody() {
        }
        
        public GetShowingResponseBody(System.Collections.Generic.List<praktikfall.WebServiceUpg2Reference.Showing> GetShowingResult) {
            this.GetShowingResult = GetShowingResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProspectiveBuyersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProspectiveBuyers", Namespace="http://brokerapplication.org/", Order=0)]
        public praktikfall.WebServiceUpg2Reference.GetProspectiveBuyersRequestBody Body;
        
        public GetProspectiveBuyersRequest() {
        }
        
        public GetProspectiveBuyersRequest(praktikfall.WebServiceUpg2Reference.GetProspectiveBuyersRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetProspectiveBuyersRequestBody {
        
        public GetProspectiveBuyersRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProspectiveBuyersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProspectiveBuyersResponse", Namespace="http://brokerapplication.org/", Order=0)]
        public praktikfall.WebServiceUpg2Reference.GetProspectiveBuyersResponseBody Body;
        
        public GetProspectiveBuyersResponse() {
        }
        
        public GetProspectiveBuyersResponse(praktikfall.WebServiceUpg2Reference.GetProspectiveBuyersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://brokerapplication.org/")]
    public partial class GetProspectiveBuyersResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<praktikfall.WebServiceUpg2Reference.ProspectiveBuyer> GetProspectiveBuyersResult;
        
        public GetProspectiveBuyersResponseBody() {
        }
        
        public GetProspectiveBuyersResponseBody(System.Collections.Generic.List<praktikfall.WebServiceUpg2Reference.ProspectiveBuyer> GetProspectiveBuyersResult) {
            this.GetProspectiveBuyersResult = GetProspectiveBuyersResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRealEstateObjectsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRealEstateObjects", Namespace="http://brokerapplication.org/", Order=0)]
        public praktikfall.WebServiceUpg2Reference.GetRealEstateObjectsRequestBody Body;
        
        public GetRealEstateObjectsRequest() {
        }
        
        public GetRealEstateObjectsRequest(praktikfall.WebServiceUpg2Reference.GetRealEstateObjectsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetRealEstateObjectsRequestBody {
        
        public GetRealEstateObjectsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRealEstateObjectsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRealEstateObjectsResponse", Namespace="http://brokerapplication.org/", Order=0)]
        public praktikfall.WebServiceUpg2Reference.GetRealEstateObjectsResponseBody Body;
        
        public GetRealEstateObjectsResponse() {
        }
        
        public GetRealEstateObjectsResponse(praktikfall.WebServiceUpg2Reference.GetRealEstateObjectsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://brokerapplication.org/")]
    public partial class GetRealEstateObjectsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<praktikfall.WebServiceUpg2Reference.RealEstateObject> GetRealEstateObjectsResult;
        
        public GetRealEstateObjectsResponseBody() {
        }
        
        public GetRealEstateObjectsResponseBody(System.Collections.Generic.List<praktikfall.WebServiceUpg2Reference.RealEstateObject> GetRealEstateObjectsResult) {
            this.GetRealEstateObjectsResult = GetRealEstateObjectsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceUpg2SoapChannel : praktikfall.WebServiceUpg2Reference.WebServiceUpg2Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceUpg2SoapClient : System.ServiceModel.ClientBase<praktikfall.WebServiceUpg2Reference.WebServiceUpg2Soap>, praktikfall.WebServiceUpg2Reference.WebServiceUpg2Soap {
        
        public WebServiceUpg2SoapClient() {
        }
        
        public WebServiceUpg2SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceUpg2SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceUpg2SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceUpg2SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        praktikfall.WebServiceUpg2Reference.GetObjectOwnerResponse praktikfall.WebServiceUpg2Reference.WebServiceUpg2Soap.GetObjectOwner(praktikfall.WebServiceUpg2Reference.GetObjectOwnerRequest request) {
            return base.Channel.GetObjectOwner(request);
        }
        
        public System.Collections.Generic.List<praktikfall.WebServiceUpg2Reference.ObjectOwner> GetObjectOwner() {
            praktikfall.WebServiceUpg2Reference.GetObjectOwnerRequest inValue = new praktikfall.WebServiceUpg2Reference.GetObjectOwnerRequest();
            inValue.Body = new praktikfall.WebServiceUpg2Reference.GetObjectOwnerRequestBody();
            praktikfall.WebServiceUpg2Reference.GetObjectOwnerResponse retVal = ((praktikfall.WebServiceUpg2Reference.WebServiceUpg2Soap)(this)).GetObjectOwner(inValue);
            return retVal.Body.GetObjectOwnerResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<praktikfall.WebServiceUpg2Reference.GetObjectOwnerResponse> praktikfall.WebServiceUpg2Reference.WebServiceUpg2Soap.GetObjectOwnerAsync(praktikfall.WebServiceUpg2Reference.GetObjectOwnerRequest request) {
            return base.Channel.GetObjectOwnerAsync(request);
        }
        
        public System.Threading.Tasks.Task<praktikfall.WebServiceUpg2Reference.GetObjectOwnerResponse> GetObjectOwnerAsync() {
            praktikfall.WebServiceUpg2Reference.GetObjectOwnerRequest inValue = new praktikfall.WebServiceUpg2Reference.GetObjectOwnerRequest();
            inValue.Body = new praktikfall.WebServiceUpg2Reference.GetObjectOwnerRequestBody();
            return ((praktikfall.WebServiceUpg2Reference.WebServiceUpg2Soap)(this)).GetObjectOwnerAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        praktikfall.WebServiceUpg2Reference.GetRealEstateBrokerResponse praktikfall.WebServiceUpg2Reference.WebServiceUpg2Soap.GetRealEstateBroker(praktikfall.WebServiceUpg2Reference.GetRealEstateBrokerRequest request) {
            return base.Channel.GetRealEstateBroker(request);
        }
        
        public System.Collections.Generic.List<praktikfall.WebServiceUpg2Reference.RealEstateBroker> GetRealEstateBroker() {
            praktikfall.WebServiceUpg2Reference.GetRealEstateBrokerRequest inValue = new praktikfall.WebServiceUpg2Reference.GetRealEstateBrokerRequest();
            inValue.Body = new praktikfall.WebServiceUpg2Reference.GetRealEstateBrokerRequestBody();
            praktikfall.WebServiceUpg2Reference.GetRealEstateBrokerResponse retVal = ((praktikfall.WebServiceUpg2Reference.WebServiceUpg2Soap)(this)).GetRealEstateBroker(inValue);
            return retVal.Body.GetRealEstateBrokerResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<praktikfall.WebServiceUpg2Reference.GetRealEstateBrokerResponse> praktikfall.WebServiceUpg2Reference.WebServiceUpg2Soap.GetRealEstateBrokerAsync(praktikfall.WebServiceUpg2Reference.GetRealEstateBrokerRequest request) {
            return base.Channel.GetRealEstateBrokerAsync(request);
        }
        
        public System.Threading.Tasks.Task<praktikfall.WebServiceUpg2Reference.GetRealEstateBrokerResponse> GetRealEstateBrokerAsync() {
            praktikfall.WebServiceUpg2Reference.GetRealEstateBrokerRequest inValue = new praktikfall.WebServiceUpg2Reference.GetRealEstateBrokerRequest();
            inValue.Body = new praktikfall.WebServiceUpg2Reference.GetRealEstateBrokerRequestBody();
            return ((praktikfall.WebServiceUpg2Reference.WebServiceUpg2Soap)(this)).GetRealEstateBrokerAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        praktikfall.WebServiceUpg2Reference.GetShowingResponse praktikfall.WebServiceUpg2Reference.WebServiceUpg2Soap.GetShowing(praktikfall.WebServiceUpg2Reference.GetShowingRequest request) {
            return base.Channel.GetShowing(request);
        }
        
        public System.Collections.Generic.List<praktikfall.WebServiceUpg2Reference.Showing> GetShowing() {
            praktikfall.WebServiceUpg2Reference.GetShowingRequest inValue = new praktikfall.WebServiceUpg2Reference.GetShowingRequest();
            inValue.Body = new praktikfall.WebServiceUpg2Reference.GetShowingRequestBody();
            praktikfall.WebServiceUpg2Reference.GetShowingResponse retVal = ((praktikfall.WebServiceUpg2Reference.WebServiceUpg2Soap)(this)).GetShowing(inValue);
            return retVal.Body.GetShowingResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<praktikfall.WebServiceUpg2Reference.GetShowingResponse> praktikfall.WebServiceUpg2Reference.WebServiceUpg2Soap.GetShowingAsync(praktikfall.WebServiceUpg2Reference.GetShowingRequest request) {
            return base.Channel.GetShowingAsync(request);
        }
        
        public System.Threading.Tasks.Task<praktikfall.WebServiceUpg2Reference.GetShowingResponse> GetShowingAsync() {
            praktikfall.WebServiceUpg2Reference.GetShowingRequest inValue = new praktikfall.WebServiceUpg2Reference.GetShowingRequest();
            inValue.Body = new praktikfall.WebServiceUpg2Reference.GetShowingRequestBody();
            return ((praktikfall.WebServiceUpg2Reference.WebServiceUpg2Soap)(this)).GetShowingAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        praktikfall.WebServiceUpg2Reference.GetProspectiveBuyersResponse praktikfall.WebServiceUpg2Reference.WebServiceUpg2Soap.GetProspectiveBuyers(praktikfall.WebServiceUpg2Reference.GetProspectiveBuyersRequest request) {
            return base.Channel.GetProspectiveBuyers(request);
        }
        
        public System.Collections.Generic.List<praktikfall.WebServiceUpg2Reference.ProspectiveBuyer> GetProspectiveBuyers() {
            praktikfall.WebServiceUpg2Reference.GetProspectiveBuyersRequest inValue = new praktikfall.WebServiceUpg2Reference.GetProspectiveBuyersRequest();
            inValue.Body = new praktikfall.WebServiceUpg2Reference.GetProspectiveBuyersRequestBody();
            praktikfall.WebServiceUpg2Reference.GetProspectiveBuyersResponse retVal = ((praktikfall.WebServiceUpg2Reference.WebServiceUpg2Soap)(this)).GetProspectiveBuyers(inValue);
            return retVal.Body.GetProspectiveBuyersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<praktikfall.WebServiceUpg2Reference.GetProspectiveBuyersResponse> praktikfall.WebServiceUpg2Reference.WebServiceUpg2Soap.GetProspectiveBuyersAsync(praktikfall.WebServiceUpg2Reference.GetProspectiveBuyersRequest request) {
            return base.Channel.GetProspectiveBuyersAsync(request);
        }
        
        public System.Threading.Tasks.Task<praktikfall.WebServiceUpg2Reference.GetProspectiveBuyersResponse> GetProspectiveBuyersAsync() {
            praktikfall.WebServiceUpg2Reference.GetProspectiveBuyersRequest inValue = new praktikfall.WebServiceUpg2Reference.GetProspectiveBuyersRequest();
            inValue.Body = new praktikfall.WebServiceUpg2Reference.GetProspectiveBuyersRequestBody();
            return ((praktikfall.WebServiceUpg2Reference.WebServiceUpg2Soap)(this)).GetProspectiveBuyersAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        praktikfall.WebServiceUpg2Reference.GetRealEstateObjectsResponse praktikfall.WebServiceUpg2Reference.WebServiceUpg2Soap.GetRealEstateObjects(praktikfall.WebServiceUpg2Reference.GetRealEstateObjectsRequest request) {
            return base.Channel.GetRealEstateObjects(request);
        }
        
        public System.Collections.Generic.List<praktikfall.WebServiceUpg2Reference.RealEstateObject> GetRealEstateObjects() {
            praktikfall.WebServiceUpg2Reference.GetRealEstateObjectsRequest inValue = new praktikfall.WebServiceUpg2Reference.GetRealEstateObjectsRequest();
            inValue.Body = new praktikfall.WebServiceUpg2Reference.GetRealEstateObjectsRequestBody();
            praktikfall.WebServiceUpg2Reference.GetRealEstateObjectsResponse retVal = ((praktikfall.WebServiceUpg2Reference.WebServiceUpg2Soap)(this)).GetRealEstateObjects(inValue);
            return retVal.Body.GetRealEstateObjectsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<praktikfall.WebServiceUpg2Reference.GetRealEstateObjectsResponse> praktikfall.WebServiceUpg2Reference.WebServiceUpg2Soap.GetRealEstateObjectsAsync(praktikfall.WebServiceUpg2Reference.GetRealEstateObjectsRequest request) {
            return base.Channel.GetRealEstateObjectsAsync(request);
        }
        
        public System.Threading.Tasks.Task<praktikfall.WebServiceUpg2Reference.GetRealEstateObjectsResponse> GetRealEstateObjectsAsync() {
            praktikfall.WebServiceUpg2Reference.GetRealEstateObjectsRequest inValue = new praktikfall.WebServiceUpg2Reference.GetRealEstateObjectsRequest();
            inValue.Body = new praktikfall.WebServiceUpg2Reference.GetRealEstateObjectsRequestBody();
            return ((praktikfall.WebServiceUpg2Reference.WebServiceUpg2Soap)(this)).GetRealEstateObjectsAsync(inValue);
        }
    }
}
