//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace praktikfall.WebServiceUpg2Reference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ObjectOwner", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ObjectOwner : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OwnerSsnrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string OwnerSsnr {
            get {
                return this.OwnerSsnrField;
            }
            set {
                if ((object.ReferenceEquals(this.OwnerSsnrField, value) != true)) {
                    this.OwnerSsnrField = value;
                    this.RaisePropertyChanged("OwnerSsnr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string PhoneNr {
            get {
                return this.PhoneNrField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNrField, value) != true)) {
                    this.PhoneNrField = value;
                    this.RaisePropertyChanged("PhoneNr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RealEstateBroker", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class RealEstateBroker : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BrokerSsnrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BrokerAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string BrokerSsnr {
            get {
                return this.BrokerSsnrField;
            }
            set {
                if ((object.ReferenceEquals(this.BrokerSsnrField, value) != true)) {
                    this.BrokerSsnrField = value;
                    this.RaisePropertyChanged("BrokerSsnr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string BrokerAddress {
            get {
                return this.BrokerAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.BrokerAddressField, value) != true)) {
                    this.BrokerAddressField = value;
                    this.RaisePropertyChanged("BrokerAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string PhoneNr {
            get {
                return this.PhoneNrField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNrField, value) != true)) {
                    this.PhoneNrField = value;
                    this.RaisePropertyChanged("PhoneNr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WebServiceUpg2Reference.WebServiceUpg2Soap")]
    public interface WebServiceUpg2Soap {
        
        // CODEGEN: Generating message contract since element name GetObjectOwnerResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetObjectOwner", ReplyAction="*")]
        praktikfall.WebServiceUpg2Reference.GetObjectOwnerResponse GetObjectOwner(praktikfall.WebServiceUpg2Reference.GetObjectOwnerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetObjectOwner", ReplyAction="*")]
        System.Threading.Tasks.Task<praktikfall.WebServiceUpg2Reference.GetObjectOwnerResponse> GetObjectOwnerAsync(praktikfall.WebServiceUpg2Reference.GetObjectOwnerRequest request);
        
        // CODEGEN: Generating message contract since element name GetRealEstateBrokerResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRealEstateBroker", ReplyAction="*")]
        praktikfall.WebServiceUpg2Reference.GetRealEstateBrokerResponse GetRealEstateBroker(praktikfall.WebServiceUpg2Reference.GetRealEstateBrokerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRealEstateBroker", ReplyAction="*")]
        System.Threading.Tasks.Task<praktikfall.WebServiceUpg2Reference.GetRealEstateBrokerResponse> GetRealEstateBrokerAsync(praktikfall.WebServiceUpg2Reference.GetRealEstateBrokerRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetObjectOwnerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetObjectOwner", Namespace="http://tempuri.org/", Order=0)]
        public praktikfall.WebServiceUpg2Reference.GetObjectOwnerRequestBody Body;
        
        public GetObjectOwnerRequest() {
        }
        
        public GetObjectOwnerRequest(praktikfall.WebServiceUpg2Reference.GetObjectOwnerRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetObjectOwnerRequestBody {
        
        public GetObjectOwnerRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetObjectOwnerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetObjectOwnerResponse", Namespace="http://tempuri.org/", Order=0)]
        public praktikfall.WebServiceUpg2Reference.GetObjectOwnerResponseBody Body;
        
        public GetObjectOwnerResponse() {
        }
        
        public GetObjectOwnerResponse(praktikfall.WebServiceUpg2Reference.GetObjectOwnerResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetObjectOwnerResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<praktikfall.WebServiceUpg2Reference.ObjectOwner> GetObjectOwnerResult;
        
        public GetObjectOwnerResponseBody() {
        }
        
        public GetObjectOwnerResponseBody(System.Collections.Generic.List<praktikfall.WebServiceUpg2Reference.ObjectOwner> GetObjectOwnerResult) {
            this.GetObjectOwnerResult = GetObjectOwnerResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRealEstateBrokerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRealEstateBroker", Namespace="http://tempuri.org/", Order=0)]
        public praktikfall.WebServiceUpg2Reference.GetRealEstateBrokerRequestBody Body;
        
        public GetRealEstateBrokerRequest() {
        }
        
        public GetRealEstateBrokerRequest(praktikfall.WebServiceUpg2Reference.GetRealEstateBrokerRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetRealEstateBrokerRequestBody {
        
        public GetRealEstateBrokerRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRealEstateBrokerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRealEstateBrokerResponse", Namespace="http://tempuri.org/", Order=0)]
        public praktikfall.WebServiceUpg2Reference.GetRealEstateBrokerResponseBody Body;
        
        public GetRealEstateBrokerResponse() {
        }
        
        public GetRealEstateBrokerResponse(praktikfall.WebServiceUpg2Reference.GetRealEstateBrokerResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetRealEstateBrokerResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<praktikfall.WebServiceUpg2Reference.RealEstateBroker> GetRealEstateBrokerResult;
        
        public GetRealEstateBrokerResponseBody() {
        }
        
        public GetRealEstateBrokerResponseBody(System.Collections.Generic.List<praktikfall.WebServiceUpg2Reference.RealEstateBroker> GetRealEstateBrokerResult) {
            this.GetRealEstateBrokerResult = GetRealEstateBrokerResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceUpg2SoapChannel : praktikfall.WebServiceUpg2Reference.WebServiceUpg2Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceUpg2SoapClient : System.ServiceModel.ClientBase<praktikfall.WebServiceUpg2Reference.WebServiceUpg2Soap>, praktikfall.WebServiceUpg2Reference.WebServiceUpg2Soap {
        
        public WebServiceUpg2SoapClient() {
        }
        
        public WebServiceUpg2SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceUpg2SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceUpg2SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceUpg2SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        praktikfall.WebServiceUpg2Reference.GetObjectOwnerResponse praktikfall.WebServiceUpg2Reference.WebServiceUpg2Soap.GetObjectOwner(praktikfall.WebServiceUpg2Reference.GetObjectOwnerRequest request) {
            return base.Channel.GetObjectOwner(request);
        }
        
        public System.Collections.Generic.List<praktikfall.WebServiceUpg2Reference.ObjectOwner> GetObjectOwner() {
            praktikfall.WebServiceUpg2Reference.GetObjectOwnerRequest inValue = new praktikfall.WebServiceUpg2Reference.GetObjectOwnerRequest();
            inValue.Body = new praktikfall.WebServiceUpg2Reference.GetObjectOwnerRequestBody();
            praktikfall.WebServiceUpg2Reference.GetObjectOwnerResponse retVal = ((praktikfall.WebServiceUpg2Reference.WebServiceUpg2Soap)(this)).GetObjectOwner(inValue);
            return retVal.Body.GetObjectOwnerResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<praktikfall.WebServiceUpg2Reference.GetObjectOwnerResponse> praktikfall.WebServiceUpg2Reference.WebServiceUpg2Soap.GetObjectOwnerAsync(praktikfall.WebServiceUpg2Reference.GetObjectOwnerRequest request) {
            return base.Channel.GetObjectOwnerAsync(request);
        }
        
        public System.Threading.Tasks.Task<praktikfall.WebServiceUpg2Reference.GetObjectOwnerResponse> GetObjectOwnerAsync() {
            praktikfall.WebServiceUpg2Reference.GetObjectOwnerRequest inValue = new praktikfall.WebServiceUpg2Reference.GetObjectOwnerRequest();
            inValue.Body = new praktikfall.WebServiceUpg2Reference.GetObjectOwnerRequestBody();
            return ((praktikfall.WebServiceUpg2Reference.WebServiceUpg2Soap)(this)).GetObjectOwnerAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        praktikfall.WebServiceUpg2Reference.GetRealEstateBrokerResponse praktikfall.WebServiceUpg2Reference.WebServiceUpg2Soap.GetRealEstateBroker(praktikfall.WebServiceUpg2Reference.GetRealEstateBrokerRequest request) {
            return base.Channel.GetRealEstateBroker(request);
        }
        
        public System.Collections.Generic.List<praktikfall.WebServiceUpg2Reference.RealEstateBroker> GetRealEstateBroker() {
            praktikfall.WebServiceUpg2Reference.GetRealEstateBrokerRequest inValue = new praktikfall.WebServiceUpg2Reference.GetRealEstateBrokerRequest();
            inValue.Body = new praktikfall.WebServiceUpg2Reference.GetRealEstateBrokerRequestBody();
            praktikfall.WebServiceUpg2Reference.GetRealEstateBrokerResponse retVal = ((praktikfall.WebServiceUpg2Reference.WebServiceUpg2Soap)(this)).GetRealEstateBroker(inValue);
            return retVal.Body.GetRealEstateBrokerResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<praktikfall.WebServiceUpg2Reference.GetRealEstateBrokerResponse> praktikfall.WebServiceUpg2Reference.WebServiceUpg2Soap.GetRealEstateBrokerAsync(praktikfall.WebServiceUpg2Reference.GetRealEstateBrokerRequest request) {
            return base.Channel.GetRealEstateBrokerAsync(request);
        }
        
        public System.Threading.Tasks.Task<praktikfall.WebServiceUpg2Reference.GetRealEstateBrokerResponse> GetRealEstateBrokerAsync() {
            praktikfall.WebServiceUpg2Reference.GetRealEstateBrokerRequest inValue = new praktikfall.WebServiceUpg2Reference.GetRealEstateBrokerRequest();
            inValue.Body = new praktikfall.WebServiceUpg2Reference.GetRealEstateBrokerRequestBody();
            return ((praktikfall.WebServiceUpg2Reference.WebServiceUpg2Soap)(this)).GetRealEstateBrokerAsync(inValue);
        }
    }
}
