//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace praktikfall.WebServiceUpg2Reference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ObjectOwner", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ObjectOwner : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OwnerSsnrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string OwnerSsnr {
            get {
                return this.OwnerSsnrField;
            }
            set {
                if ((object.ReferenceEquals(this.OwnerSsnrField, value) != true)) {
                    this.OwnerSsnrField = value;
                    this.RaisePropertyChanged("OwnerSsnr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string PhoneNr {
            get {
                return this.PhoneNrField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNrField, value) != true)) {
                    this.PhoneNrField = value;
                    this.RaisePropertyChanged("PhoneNr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WebServiceUpg2Reference.WebServiceUpg2Soap")]
    public interface WebServiceUpg2Soap {
        
        // CODEGEN: Generating message contract since element name GetObjectOwnerResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetObjectOwner", ReplyAction="*")]
        praktikfall.WebServiceUpg2Reference.GetObjectOwnerResponse GetObjectOwner(praktikfall.WebServiceUpg2Reference.GetObjectOwnerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetObjectOwner", ReplyAction="*")]
        System.Threading.Tasks.Task<praktikfall.WebServiceUpg2Reference.GetObjectOwnerResponse> GetObjectOwnerAsync(praktikfall.WebServiceUpg2Reference.GetObjectOwnerRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetObjectOwnerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetObjectOwner", Namespace="http://tempuri.org/", Order=0)]
        public praktikfall.WebServiceUpg2Reference.GetObjectOwnerRequestBody Body;
        
        public GetObjectOwnerRequest() {
        }
        
        public GetObjectOwnerRequest(praktikfall.WebServiceUpg2Reference.GetObjectOwnerRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetObjectOwnerRequestBody {
        
        public GetObjectOwnerRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetObjectOwnerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetObjectOwnerResponse", Namespace="http://tempuri.org/", Order=0)]
        public praktikfall.WebServiceUpg2Reference.GetObjectOwnerResponseBody Body;
        
        public GetObjectOwnerResponse() {
        }
        
        public GetObjectOwnerResponse(praktikfall.WebServiceUpg2Reference.GetObjectOwnerResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetObjectOwnerResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<praktikfall.WebServiceUpg2Reference.ObjectOwner> GetObjectOwnerResult;
        
        public GetObjectOwnerResponseBody() {
        }
        
        public GetObjectOwnerResponseBody(System.Collections.Generic.List<praktikfall.WebServiceUpg2Reference.ObjectOwner> GetObjectOwnerResult) {
            this.GetObjectOwnerResult = GetObjectOwnerResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceUpg2SoapChannel : praktikfall.WebServiceUpg2Reference.WebServiceUpg2Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceUpg2SoapClient : System.ServiceModel.ClientBase<praktikfall.WebServiceUpg2Reference.WebServiceUpg2Soap>, praktikfall.WebServiceUpg2Reference.WebServiceUpg2Soap {
        
        public WebServiceUpg2SoapClient() {
        }
        
        public WebServiceUpg2SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceUpg2SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceUpg2SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceUpg2SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        praktikfall.WebServiceUpg2Reference.GetObjectOwnerResponse praktikfall.WebServiceUpg2Reference.WebServiceUpg2Soap.GetObjectOwner(praktikfall.WebServiceUpg2Reference.GetObjectOwnerRequest request) {
            return base.Channel.GetObjectOwner(request);
        }
        
        public System.Collections.Generic.List<praktikfall.WebServiceUpg2Reference.ObjectOwner> GetObjectOwner() {
            praktikfall.WebServiceUpg2Reference.GetObjectOwnerRequest inValue = new praktikfall.WebServiceUpg2Reference.GetObjectOwnerRequest();
            inValue.Body = new praktikfall.WebServiceUpg2Reference.GetObjectOwnerRequestBody();
            praktikfall.WebServiceUpg2Reference.GetObjectOwnerResponse retVal = ((praktikfall.WebServiceUpg2Reference.WebServiceUpg2Soap)(this)).GetObjectOwner(inValue);
            return retVal.Body.GetObjectOwnerResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<praktikfall.WebServiceUpg2Reference.GetObjectOwnerResponse> praktikfall.WebServiceUpg2Reference.WebServiceUpg2Soap.GetObjectOwnerAsync(praktikfall.WebServiceUpg2Reference.GetObjectOwnerRequest request) {
            return base.Channel.GetObjectOwnerAsync(request);
        }
        
        public System.Threading.Tasks.Task<praktikfall.WebServiceUpg2Reference.GetObjectOwnerResponse> GetObjectOwnerAsync() {
            praktikfall.WebServiceUpg2Reference.GetObjectOwnerRequest inValue = new praktikfall.WebServiceUpg2Reference.GetObjectOwnerRequest();
            inValue.Body = new praktikfall.WebServiceUpg2Reference.GetObjectOwnerRequestBody();
            return ((praktikfall.WebServiceUpg2Reference.WebServiceUpg2Soap)(this)).GetObjectOwnerAsync(inValue);
        }
    }
}
